global:
  evaluation_interval: 15s
  query_log_file: prometheus.log
  scrape_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
- rules/*.yml
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
  file_sd_configs: []
- job_name: node
  file_sd_configs:
  - files:
    - sd/file/node/*.yaml
    - sd/file/node/*.json
- job_name: mysql
  file_sd_configs:
  - files:
    - sd/file/mysql/*.yaml
    - sd/file/mysql/*.json
- job_name: redis
  file_sd_configs:
  - files:
    - sd/file/redis/*.yaml
    - sd/file/redis/*.json
